### ISSUE TITLE
Object masks generation for custom recordings

### ISSUE THREAD

**Issue by niemiaszek** [MCG-NKU/E2FGVI#1]
Amazing paper and results, thanks for this work! I can't wait to see future updates described in _Work in Progress_ section!
I'm interested in testing your method for object removal task on my custom videos outside of popular benchmarks. I was wondering if you could recommend any method for producing these object masks - hopefully generating one mask per object in video?

**Comment by Paper99** [comment]
Thank you. We obtain these object masks with the help of interactive segmentation methods.
Here are some awesome repos:
1. https://github.com/hkchengrex/MiVOS
2. https://github.com/frazerlin/fcanet

I hope this could help you.

**Comment by niemiaszek** [comment]
Thank you very much for your recommendations!
