### ISSUE TITLE
Environment configuration

### ISSUE THREAD

**Issue by LigZhong** [MCG-NKU/E2FGVI#10]
Hi, I tried to modify the environment for training to resolve the problem incurred by DCN v2 as mentioned in #6 but things did not work out. I could not use your original configuration, which I haven't figured out why. Probably due to driver version of CUDA or something else. I tried to resume from the ckpt before loss curve goes high but did not work. I would like to follow your original configuration. Can you give some information about the system and driver version of your CUDA? Thanks a lot.

**Comment by Paper99** [comment]
For environment settings, you can follow [this reply](https://github.com/MCG-NKU/E2FGVI/issues/3#issuecomment-1096780387).

We developed our model on Ubuntu 18.04.
The CUDA driver version is 440.82.

To the best of my knowledge, I don't think these settings will affect the instability of the training.
If resuming training still did not work for your model, you could consider to re-train a new one.
