### ISSUE TITLE
Output encoding settings

### ISSUE THREAD

**Issue by 8Dataman8** [MCG-NKU/E2FGVI#11]
Hello. After a long while of trial and error, I managed to get this software running. It still doesn't run well, giving me OOM with more than 250 frames of 120x144 video. I have an 8GB 3060ti, which should be fine for this, in my opinion. Needing to split tasks many times is a pain, but might be manageable.

What isn't manageable are the output settings. H.263 is outdated and with tiny input sizes and lengths, lossy is a baffling pick. Maybe I missed a customizing option somewhere? I would like to have lossless h264 or FFV1. In addition, I would like to decide the video's framerate (very important for syncing) and not have the video resized. That causes distortions that look bad.

Thank you. Looking forward to the high-resolution model.

**Comment by Paper99** [comment]
You could change the value of [this flag](https://github.com/MCG-NKU/E2FGVI/blob/206b3318d0cf76bf78e8e121216c15c35abcbad9/test.py#L28) to determine the framerate of the saving video.

For arbitrary resolution model, we plan to release it at May 15, 2022.

**Comment by 8Dataman8** [comment]
Thank you for your quick answer. Is there a way to set it to automatically get the FPS from the source video?

**Comment by Paper99** [comment]
Now our test script doesn't support these features you mentioned.
You may need to refine it according to your demand.

**Comment by 8Dataman8** [comment]
Alright. Thanks again for your speedy reply. I'll try to figure something out. Looking forward to the free resolution mode. Peace!
