### ISSUE TITLE
About Training

### ISSUE THREAD

**Issue by caimaomao315** [MCG-NKU/E2FGVI#16]
您好呀，最近在阅读此模型的论文及代码调试
我有两个问题想咨询一下您
1. 有关数据集，以下是我的路径
![1](https://user-images.githubusercontent.com/61854190/168950213-b907bcab-4fa0-464f-9574-db46c1d3fa81.jpg)

在我输入命令: :/data/team10/cai/E2FGV$ sh datasets/zip_dir.sh
出现文件不存在:[./datasets/davis/JPEGImages] is not exist. Please check the directory.
Done!
我想知道我的路径这样是出错了嘛~
2.第二个，在训练期间无法获取GPU，（服务器上有6张显卡，我最近一次调用有2张剩余）
![屏幕截图 2022-05-18 110907](https://user-images.githubusercontent.com/61854190/168949306-d19a0aea-35e7-4a08-9045-c4393c968e1e.jpg)
config['world_size'] = get_world_size()获取的数量为0

**Comment by LGYoung** [comment]
1. zip_dir.sh 需要放在base目录下去运行，需要大概阅读脚本内容再去执行
2. 运行环境存在问题，可以遵从[issue](https://github.com/MCG-NKU/E2FGVI/issues/3) 去配置环境

**Comment by DidaDidaDidaD** [comment]
> 1. zip_dir.sh 需要放在base目录下去运行，需要大概阅读脚本内容再去执行
> 2. 运行环境存在问题，可以遵从[issue](https://github.com/MCG-NKU/E2FGVI/issues/3) 去配置环境

从zip_dir.sh内容看，问题就出在if  [ -f $folder ];then，应该为if  [ -d $folder ];then，人家目录放的没问题
