### ISSUE TITLE
About Speed Test~

### ISSUE THREAD

**Issue by MasterHow** [MCG-NKU/E2FGVI#30]
作者您好，感谢您的精彩工作！我从中学到了许多 =)
请问速度的测试是在Davis数据集上以480x854的分辨率，计算一次forward时间并除以len(neighbor_ids)得到的吗？

**Comment by Paper99** [comment]
您好，感谢您的关注。
速度测试时，输入视频的分辨率为432 x 240，计算的是整个视频forward完后的时间再除以视频帧数。

**Comment by MasterHow** [comment]
收到，感谢您的耐心回复
