### ISSUE TITLE
frame_idx和flow_idx

### ISSUE THREAD

**Issue by Roowenliang** [MCG-NKU/E2FGVI#33]
[syujung] 在七月20号 问了以下这个问题（Issue#25）
“作者您好，您的这片工作非常精彩，效果也很棒！
我有一个关于代码的问题，您上传的代码models/modules/feat_prop.py里面，我对比了一下basicvsr++的源码，感觉在backward_propagation的时候，得到cond_n1所用的光流是不是有问题，您写的for循环frame_idx和flow_idx应该保持顺序一致？我看basicvsr++是这样的，想询问一下”

您可以具体说一下应该怎样修改现在的代码？多谢！

**Comment by Paper99** [comment]
https://github.com/MCG-NKU/E2FGVI/blob/924b56c133fffe37327f9c9b90290fc3d0538581/model/modules/feat_prop.py#L100

该行下加入

```python
    flow_idx = frame_idx
```

**Comment by Roowenliang** [comment]
Thanks!

**Comment by sydney0zq** [comment]
> https://github.com/MCG-NKU/E2FGVI/blob/924b56c133fffe37327f9c9b90290fc3d0538581/model/modules/feat_prop.py#L100
> 
> 该行下加入
> 
> ```python
>     flow_idx = frame_idx
> ```

@Paper99 这里确认是有一个bug是么，我打印了下好像flow和frame idx确实没有一致，以及https://github.com/MCG-NKU/E2FGVI/blob/924b56c133fffe37327f9c9b90290fc3d0538581/model/modules/feat_prop.py#L81 这行的forward和backward不一致应该也是一个问题？

```
[backward_]: loop i 0, frame idx 4, flow idx -1
[backward_]: loop i 1, frame idx 3, flow idx 0
[backward_]: loop i 2, frame idx 2, flow idx 1
[backward_]: loop i 3, frame idx 1, flow idx 2
[backward_]: loop i 4, frame idx 0, flow idx 3
[forward_]: loop i 0, frame idx 0, flow idx -1
[forward_]: loop i 1, frame idx 1, flow idx 0
[forward_]: loop i 2, frame idx 2, flow idx 1
[forward_]: loop i 3, frame idx 3, flow idx 2
[forward_]: loop i 4, frame idx 4, flow idx 3
```
