### ISSUE TITLE
About the pretrained model of discriminator and opt.pth

### ISSUE THREAD

**Issue by nlx0021** [MCG-NKU/E2FGVI#35]
Hello, I'm very lucky and happy to know your work. What a fantastic work!
I am doing some research which also contains video inpainting. I'd like to finetune your pretrained model on my new dataset. However, I could only find the generator model in the link given in README.md. Could you please upload the discriminator model as well (also the opt.pth)? Or could you please tell me how to get access to it in case I missed the downloading link?
Thank you very much!

**Comment by Paper99** [comment]
OK, we will update it ASAP.

**Comment by nlx0021** [comment]
Thank you very much!
I will download it and close this issue. Have a nice day!

**Comment by ywj-github** [comment]
> 

Hello, how can I find the .pth files of other modules. Thank you very much!

**Comment by MasterHow** [comment]
: )
