### ISSUE TITLE
Question of Focal Transformer

### ISSUE THREAD

**Issue by sydney0zq** [MCG-NKU/E2FGVI#47]
Hey, thanks for your wonderful work. I think it may be a bug: https://github.com/MCG-NKU/E2FGVI/blob/924b56c133fffe37327f9c9b90290fc3d0538581/model/modules/tfocal_transformer.py#L342,

should we first transpose and then do view operation?

Thanks in advance!

**Comment by NK-CS-ZZL** [comment]
Could you describe your issue in detail and explain why we should first transpose it?

**Comment by sydney0zq** [comment]
@NK-CS-ZZL In Line 332, the `k_pooled_k`'s dim is `B*nWh/S*nWw/S T*Kh*Kw nC Cs`, if we view it as  

```
                k_pooled_k = k_pooled_k.view(
                    -1, self.num_heads, T * self.unfolds[k].kernel_size[0] *
                    self.unfolds[k].kernel_size[1], C // self.num_heads)
```

the `self.num_heads` will be not correct. Therefore, the correct version may be as follows:

```
#k/v_pooled_k: B*nWh/S*nWw/S T Kh*Kw nC Cs --view--> B*nWh/S*nWw/S T*Kh*Kw nC Cs --transpose--> B*nWh/S*nWw/S nC T*Kh*Kw Cs
k_pooled_k = k_pooled_k.view(-1, T*unfold_kh*unfold_kw, self.num_heads, C//self.num_heads).transpose(1, 2)
v_pooled_k = v_pooled_k.view(-1, T*unfold_kh*unfold_kw, self.num_heads, C//self.num_heads).transpose(1, 2)
```

**Comment by NK-CS-ZZL** [comment]
Thanks for your detailed reply. However, I still have some questions and hope a further explanation.
In Line 331, there are other `permute` & `view` operator which re-order `k_pooled_k` into (num_tokens, num_heads, T, win_size, dim). I didn't see you mention it in the explanation, so did you miss it or I didn't fully understand your comment.

**Comment by sydney0zq** [comment]
@NK-CS-ZZL Sorry, it is my mistake. The official code has no problem here. Thanks for your reply.

By the way, how do you visualize the features? just average along the channel axis?

**Comment by NK-CS-ZZL** [comment]
I didn't participate this part of the paper, and @Paper99 knows this detail. I guess a simple average is enough.

**Comment by sydney0zq** [comment]
Thanks for you detailed reply.
