### ISSUE TITLE
关于FLOPs计算的代码

### ISSUE THREAD

**Issue by unclebuff** [MCG-NKU/E2FGVI#5]
作者您好，
我也一直在关注这方面的工作。由于注意力计算的存在，STTN和Fusefomer等工作的FLOPs难以用现有的模型统计插件计算，请问作者是否可以提供一些您在报告FLOPs指标时使用的代码或者计算方法，以方便我们更好的跟进您的工作。谢谢

**Comment by Paper99** [comment]
推荐使用[fvcore](https://github.com/facebookresearch/fvcore)进行FLOPs的计算。
推荐阅读[fvcore官方文档](https://github.com/facebookresearch/fvcore/blob/main/docs/flop_count.md)以了解该计算工具相较于多数FLOPs计算工具的优势。
此外，对于attention的FLOPs计算，推荐查阅[Focal Transformer](https://github.com/microsoft/Focal-Transformer/blob/main/classification/focal_transformer.py)以及[Swin Transformer](https://github.com/microsoft/Swin-Transformer/blob/main/models/swin_transformer.py)的相关函数。
