### ISSUE TITLE
Error reported in training <IndexError: list index out of range>

### ISSUE THREAD

**Issue by Lynchrocket** [MCG-NKU/E2FGVI#51]
作者您好！最近在阅读您的这篇文章及尝试调试代码。我有一个问题想咨询您。
在使用youtube-vos数据集来训练e2fgvi模型时，出现了以下问题。

![1](https://user-images.githubusercontent.com/77106522/200557170-002abf70-85e2-4f00-8f76-a1c8349a3534.png)

索引越界了。
查看 datasets/youtube-vos/train.json 这个文件，猜测是“数据编号:帧数量”的意思，例如 "003234408d": 180 的意思是youtube-vos数据集里面编号为003234408d的数据一共有180帧。可是 datasets/youtube-vos/JPEGImages 这个文件夹里面并没有编号为003234408d的数据，因此我猜测可能是我下载的数据集出错了。但是我是按照着Prepare dataset for training and evaluation的指引下载了[youtube-vos2018](https://competitions.codalab.org/competitions/19544#participate)（或者[Google Drive](https://drive.google.com/drive/folders/1bI5J1H3mxsIGo7Kp-pPZU8i6rnykOw7f)）的train.zip和test_all_frames.zip这两个文件并解压，mask也用的是指引提供的。
是因为我弄错了数据集吗？

**Comment by DidaDidaDidaD** [comment]
遇到了同样的问题，越界

**Comment by DidaDidaDidaD** [comment]
补充一下，003234408d这个数据集里是有的，你下的可能数据集有问题，但里面的数据多多少少有些问题，不行就将有问题的去掉或者替换一下，写个脚本匹配一下

**Comment by Lynchrocket** [comment]
谢谢 DidaDidaDidaD 大佬。用脚本将train.json和test.json改一下确实就可以了。但是我又遇到了 #12 的问题，请问大佬有遇到这个问题吗，有的话要如何解决呢。（我已经尝试过 #3 的方案了）

**Comment by Lynchrocket** [comment]
> 补充一下，003234408d这个数据集里是有的，你下的可能数据集有问题，但里面的数据多多少少有些问题，不行就将有问题的去掉或者替换一下，写个脚本匹配一下

谢谢 DidaDidaDidaD 大佬。用脚本将train.json和test.json改一下确实就可以了。但是我又遇到了 https://github.com/MCG-NKU/E2FGVI/issues/12 的问题，请问大佬有遇到这个问题吗，有的话要如何解决呢。（我已经尝试过 https://github.com/MCG-NKU/E2FGVI/issues/3 的方案了）

**Comment by DidaDidaDidaD** [comment]
> 
我也是小白哈，这个问题我没遇到过，既然作者提到很可能是mmcv引起的，那应该就是了，安装mmcv-full有很多方式，例如pip install mmcv-full这种肯定用不了，我用过可以用的就一种，就是pip install mmcv-full=={mmcv_version} -f https://download.openmmlab.com/mmcv/dist/{cuda_version}/{torch_version}/index.html，如pip install mmcv-full==1.4.2 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html，mmcv-full的版本需要你的pytorch版本匹配，具体可以去mmcv git页面上看


> > 补充一下，003234408d这个数据集里是有的，你下的可能数据集有问题，但里面的数据多多少少有些问题，不行就将有问题的去掉或者替换一下，写个脚本匹配一下
> 
> 谢谢 DidaDidaDidaD 大佬。用脚本将train.json和test.json改一下确实就可以了。但是我又遇到了 #12 的问题，请问大佬有遇到这个问题吗，有的话要如何解决呢。（我已经尝试过 #3 的方案了）

**Comment by Lynchrocket** [comment]
> > 
> 
> 我也是小白哈，这个问题我没遇到过，既然作者提到很可能是mmcv引起的，那应该就是了，安装mmcv-full有很多方式，例如pip install mmcv-full这种肯定用不了，我用过可以用的就一种，就是pip install mmcv-full=={mmcv_version} -f [https://download.openmmlab.com/mmcv/dist/{cuda_version}/{torch_version}/index.html，如pip](https://download.openmmlab.com/mmcv/dist/%7Bcuda_version%7D/%7Btorch_version%7D/index.html%EF%BC%8C%E5%A6%82pip) install mmcv-full==1.4.2 -f [https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html，mmcv-full的版本需要你的pytorch版本匹配，具体可以去mmcv](https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/index.html%EF%BC%8Cmmcv-full%E7%9A%84%E7%89%88%E6%9C%AC%E9%9C%80%E8%A6%81%E4%BD%A0%E7%9A%84pytorch%E7%89%88%E6%9C%AC%E5%8C%B9%E9%85%8D%EF%BC%8C%E5%85%B7%E4%BD%93%E5%8F%AF%E4%BB%A5%E5%8E%BBmmcv) git页面上看
> 
> > > 补充一下，003234408d这个数据集里是有的，你下的可能数据集有问题，但里面的数据多多少少有些问题，不行就将有问题的去掉或者替换一下，写个脚本匹配一下
> > 
> > 
> > 谢谢 DidaDidaDidaD 大佬。用脚本将train.json和test.json改一下确实就可以了。但是我又遇到了 #12 的问题，请问大佬有遇到这个问题吗，有的话要如何解决呢。（我已经尝试过 #3 的方案了）

很抱歉回复晚了，感谢 DidaDidaDidaD 大佬。上周在问了这个问题后不久我再次重装 mmcv-full 就成功训练起来了。不知道是什么原因，但是重装多几次 mmcv-full 就可以了。
