### ISSUE TITLE
Question about the method of saving inference result

### ISSUE THREAD

**Issue by chhkang** [MCG-NKU/E2FGVI#55]
Hi, thanks for your contribution. I am very inspired by your work.
I have one question. Is there any specific reason to make the final result with the code `comp_frames[idx] = comp_frames[idx].astype(np.float32) * 0.5 + img.astype(np.float32) * 0.5` ? Since this code will add the last made one with weighted value 0.5, and previous made result impacts are decreased by half, so the result will be biased to the result that made with end neighbor frame result. Is this a common way to make the video inpainting result?

**Comment by Teravus** [comment]
I'm not convinced that it reaches that line of code very often.    
If it does, it mixes the two completed frames.

@chhkang Double check me, of course.  I've been hacking the test script to allow for arbitrary frame length..  and the only time I noticed it reach that line was when I broke it.
