### ISSUE TITLE
Not able to reproduce the results listed in the paper with my trained model

### ISSUE THREAD

**Issue by LigZhong** [MCG-NKU/E2FGVI#6]
I met a problem of mode collapse when step number is larger than 300K, and with the final model I got, I am not able to reproduce the result shown int the paper. Can you give you loss curve? @MingMingCheng

**Comment by Paper99** [comment]
Please refer to [this reply](https://github.com/MCG-NKU/E2FGVI/issues/7#issuecomment-1116935910).
