### ISSUE TITLE
关于Encoder的解释

### ISSUE THREAD

**Issue by Ballbo5354** [MCG-NKU/E2FGVI#61]
你好，想请教一下你们的Encoder部分使用了分离卷积，请问这样做的目的是什么呢？看论文好像没有分析这部分内容

**Comment by Ballbo5354** [comment]
我看到了FuseFormer也用了这个结构，本人小白，因为video inpainting任务感兴趣，所以想请教一下这部分涉及的知识。

**Comment by Paper99** [comment]
This design could refer to [DSTT](https://github.com/ruiliu-ai/DSTT).

**Comment by Ballbo5354** [comment]
> This design could refer to [DSTT](https://github.com/ruiliu-ai/DSTT).

get it. thanks
