### ISSUE TITLE
Issue in loading HQ model?

### ISSUE THREAD

**Issue by JHLew** [MCG-NKU/E2FGVI#69]
Hi, I ran into an issue while trying out the hq model, but seems like the checkpoint has an error.

RuntimeError: Error(s) in loading state_dict for InpaintGenerator:
	Missing key(s) in state_dict: "sc.bias_conv.weight", "sc.bias_conv.bias". 
	Unexpected key(s) in state_dict: "sc.bias". 

I wish to try out this hq version,
so could you kindly check out the uploaded checkpoint if it is compatible with the current repo?

**Comment by chris-hndz** [comment]
I had that message too, and I realized that the error is that in the line
python test.py --model **e2fgvi** ... 

it should read: 
python test.py --model **e2fgvi_hq** ...

You always have to change the **model** variable and the **ckpt** variable with the HQ.
