### ISSUE TITLE
训练配置及用时

### ISSUE THREAD

**Issue by quhaoooo** [MCG-NKU/E2FGVI#8]
作者太强了，不仅效果好还把开源做的这么棒，咨询一下您训练的时候用了几张卡，跑完500k iteration要花费多长时间呢。

**Comment by Paper99** [comment]
您好，感谢你的关注。我们使用8卡V100或8卡1080ti进行训练。8卡V100需要训练约5天时间，8卡1080Ti需要训练约一周。
