### ISSUE TITLE
BidirectionalPropagation 参数顺序问题

### ISSUE THREAD

**Issue by Edwardyan1112** [MCG-NKU/E2FGVI#80]
您好，请问InpaintGenerator类中forward_bidirect_flow方法中依次返回pred_flows_forward, pred_flows_backward，而调用的BidirectionalPropagation实例中，参数的顺序应当是pred_flows_backward, pred_flows_forward，而输入参数为pred_flows_forward, pred_flows_backward，这里是否反了？
![image](https://github.com/MCG-NKU/E2FGVI/assets/59927929/35d265da-7fee-4e40-96d4-e5575bb9eefc)
![image](https://github.com/MCG-NKU/E2FGVI/assets/59927929/05e0227a-a6ea-4c63-8c13-2d94e8698813)

**Comment by ZhangBing00** [comment]
我也发现了这个问题，请问您解决了吗？

**Comment by Paper99** [comment]
这个地方没有问题 我们是故意这么写的 函数外用的严格的flow定义 函数内的命名用的传递的方向

ZhangBing00 ***@***.***>于2024年1月24日 周三22:55写道：

**Comment by ZhangBing00** [comment]
好的，感谢您的回复！
